### ISSUE TITLE
Large LightGBM causes javac error "Code too Large"

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [BayesWitnesses/m2cgen#103]
When generating code for a large number of trees, the generated code exceeds the 64KB limit in java. 

From [Stackoverflow](https://stackoverflow.com/questions/2407912/code-too-large-compilation-error-in-java)
> A single method in a Java class may be at most 64KB of bytecode.

One solution is to add subfunctions https://github.com/BayesWitnesses/m2cgen/blob/master/m2cgen/assemblers/boosting.py#L43-L48 instead of having the body of every tree inside `subroutine0`. The amount of code that will fit inside each function is dependent on its depth + width so we might require some heuristic or tunable parameter. In my case, I ended up with 10 trees per subfunction

I'm not sure if there are similar limits in other languages

**Comment by izeigerman** [comment]
Hey @chris-smith-zocdoc! 

This is rather weird because we're aware of this Java limitations and this is why we came up with subroutines in the first place. I remember testing this implementation with as many as 500 - 1000 estimators with XGBoost, LightGBM and Random Forest without any problem. 

Can you please provide some steps to reproduce this issue locally? Ideally using some public dataset or the one available in the scikit-learn package?

**Comment by chris-smith-zocdoc** [comment]
I think the issue is that the trees are not in separate subroutines 
![image](https://user-images.githubusercontent.com/2537809/65980281-d68d3c00-e444-11e9-8aef-428183604270.png)

To reproduce
```python
import lightgbm as lgb
import m2cgen as m2c
import numpy as np


N = 10000
np.random.seed(seed=7)
data = np.random.random(size=(N, 200))
target = np.random.random(size=(N, 1))


estimator = lgb.LGBMRegressor(n_estimators=100, random_state=1, max_depth=64, num_leaves=100)

estimator.fit(data, target)

res = m2c.export_to_java(estimator)


with open('Model.java', 'w') as f:
    f.write(res)
```

Then

```
javac Model.java
```

**Comment by izeigerman** [comment]
Ah, I see. So the individual tree is pretty large. Ok, we may want to consider to wrap individual estimators in their own subroutines based on some threshold values for `max_depth` and `num_leaves`.

**Comment by MilanCugur** [comment]
Hi, the same situation happens with large (sklearns) decision trees. 

Do you have a solution for that (is it planned if it doesn't exist?)

**Comment by izeigerman** [comment]
Hey @MilanCugur ! Please take a look at the following discussion - https://github.com/BayesWitnesses/m2cgen/issues/297. The workaround mentioned there may potentially help with your issue.
