### ISSUE TITLE
add option to save generated code into file

### ISSUE THREAD

**Issue by StrikerRUS** [BayesWitnesses/m2cgen#110]
I'm sorry if I missed this functionality, but `CLI` version hasn't it for sure (I saw the related code only in `generate_code_examples.py`). I guess it will be very useful to eliminate copy-paste phase, especially for large models.

Of course, piping is a solution, but not for development in Jupyter Notebook, for example.

**Comment by izeigerman** [comment]
Hey @StrikerRUS, thanks for reporting this. Can `m2cgen` be used as a library in a Jupyter Notebook scenario?

**Comment by StrikerRUS** [comment]
@izeigerman Why not?.. I just used it so for preparing #109.

**Comment by izeigerman** [comment]
Yeah, I'm just trying to understand whether piping is sufficient after all or not.

**Comment by eafpres** [comment]
Just a comment; I started working on this today and the docs could be upgraded to clarify that CLI use can use piping to save to a file.  I "might" try to tackle this as I would like to get my feet wet on contributing to OSS.

**Comment by izeigerman** [comment]
@eafpres Do you mean docs of the CLI tool itself or the README? We do mention this in the latter: https://github.com/BayesWitnesses/m2cgen#cli . In any case please feel free to submit a PR. Contributions are welcome!

**Comment by eafpres** [comment]
@izeigerman Initially I was going to propose a change to the readme.  Piping works fine on the CLI so I don't see an urgent need to explicitly add the functionality to that tool.  Long-term maybe.

**Comment by wbadry** [comment]
Hello,
Is there any example showing how to save the model to a specific path?. This would be very helpful as I try several models to run in the background and would appreciate if models can be saved in a folder after each iteration. 

![bitmoji](https://sdk.bitmoji.com/render/panel/9e7d87c8-487f-4eef-85ba-e8330f464a38-ce799e56-1826-40b9-b38a-662f1607776a-v1.png?transparent=1&palette=1&width=246)

**Comment by izeigerman** [comment]
Hey @wbadry!

If you're using `m2cgen` in CLI you can just redirect its `stdout` into the file. Eg:
```
$ m2cgen <path_to_model> --language c > <path_to_output_file>
```
Alternatively if you're using the Python API:
```python
import m2cgen as m2c

generated_code = m2c.export_to_c(...)
with open('<path_to_output_file', 'w') as fd:
    fd.write(generated_code)
```
Hope this helps!

**Comment by StrikerRUS** [comment]
Closing due to the lack of interest.
