### ISSUE TITLE
Can Support Batch Predictor?

### ISSUE THREAD

**Issue by Jie-Yuan** [BayesWitnesses/m2cgen#113]
Can Support Batch Predictor?

**Comment by izeigerman** [comment]
Hi @Jie-Yuan ! Can you please share the motivation behind your request to support batch prediction? The existing API can be used in batch fashion pretty easily.

**Comment by Jie-Yuan** [comment]
Online batch prediction service

**Comment by izeigerman** [comment]
@Jie-Yuan the question is rather why existing API doesn't work for you?

**Comment by izeigerman** [comment]
Closing this due to lack of clear use case and problem description.
