### ISSUE TITLE
How to run generated java code without main method?

### ISSUE THREAD

**Issue by fakhrulfa** [BayesWitnesses/m2cgen#117]
Sorry, i newbie in java. But i need to run this code for ML program.

how to run this code 
`public class Model {

    public static double score(double[] input) {
        return (((((((((((((36.45948838508965) + ((input[0]) * (-0.10801135783679647))) + ((input[1]) * (0.04642045836688297))) + ((input[2]) * (0.020558626367073608))) + ((input[3]) * (2.6867338193449406))) + ((input[4]) * (-17.76661122830004))) + ((input[5]) * (3.8098652068092163))) + ((input[6]) * (0.0006922246403454562))) + ((input[7]) * (-1.475566845600257))) + ((input[8]) * (0.30604947898516943))) + ((input[9]) * (-0.012334593916574394))) + ((input[10]) * (-0.9527472317072884))) + ((input[11]) * (0.009311683273794044))) + ((input[12]) * (-0.5247583778554867));
    }
}`

without main code, im a bit confusing. thanks!

**Comment by izeigerman** [comment]
Hey @fakhrulfa! To keep things simple you may do one of the following:
1. Copy the Model.java file into your project. Create a class with the main method and invoke the generated model from it. Eg. you project structure can be something like this:
```
 | src/
 | | main/
 | | | java/
 | | | | com/
 | | | | | example/
 | | | | | | Main.java
 | | | | | | Model.java
```
Then you can invoke the `score` method from you main class:
```java
public class Main {

  public static void main(String[] args) {
     Model.score(...);
  }
}
```
2. To try the code in a quick a dirty way just add the main method to the `Model` class and run it instead:
```java
public class Model {
  public static void main(String[] args) {
    score(...)
  }

  public static double score(double[] input) {
  ...
}
```

**Comment by monisha08041998** [comment]
what is the input argument that is to be passed?
