### ISSUE TITLE
add support for declarative languages

### ISSUE THREAD

**Issue by StrikerRUS** [BayesWitnesses/m2cgen#127]
It seems that especially for functional languages it is very common to write `Score()` function and apply it to some data.

At present, assemblers make assumption about that target language is imperative.

**Comment by izeigerman** [comment]
Hey @StrikerRUS. Not sure I understand what you mean. Assemblers make no assumptions of this sort. The entire AST that comes out of assembler is a single expression which can be interpreted in a purely functional fashion. Except for perhaps Subroutines which can be safely ignored if needed.
Perhaps you can give a more specific example?

**Comment by StrikerRUS** [comment]
Hmmm, then seems that the base classes of code generator and interpreter confused me when suggested to override variable definition and if statement.

**Comment by izeigerman** [comment]
> then seems that the base classes of code generator and interpreter confused me when suggested to override variable definition and if statement.

That's true. So far we only added support for imperative languages and we haven't had need/demand to add functional ones. This is why the current interpreter/codegen class hierarchy only reflects imperative style. The AST and assemblers, however, have no coupling of this sort.

**Comment by StrikerRUS** [comment]
Thank you very much for the detailed explanation!
Feel free to close the issue. Or you can leave it as a feature request 🙂 .
