### ISSUE TITLE
Planned support for sklearn pipelines?

### ISSUE THREAD

**Issue by mattc-eostar** [BayesWitnesses/m2cgen#141]
Is there any conceivable way to convert a pipeline that includes other steps like feature extractions, etc?

I know this would be quite the undertaking if not currently supported. Just really love the idea of converting to no dependencies to move ML functionality to the edge. Great work!

Thanks!

**Comment by izeigerman** [comment]
Hey @mattc-eostar! 

I was considering that but at the end concluded that the majority of preprocessing steps (like standardization, MVI, etc.) are trivial enough that it shouldn't be too big of deal to implement them in a language of choice. Though I very much agree that it'd be fantastic to have support for sklearn preprocessors in `m2cgen`. 

Another concern that prevented me from introducing this - is that from my past experience more often than not people tend to use a lot of custom transformers in their pipelines . Eg. things like outlier removal, more advanced MVI strategies are missing in sklearn. 

It only makes sense to generate the code for the entire pipeline, and with custom transformers it's impossible to achieve. As a result a feature like this may end up covering only a small number of use cases.

It'd be interesting to collect some feedback from other folks in the field.

**Comment by mattc-eostar** [comment]
That is a good point. I guess I was just thinking along the lines of basic operations from the sklearn preprocessing namespace for convenience purposes. But you are right, it may not appease a lot of use cases. But if you were to come up with a way to generate agnostic code for those steps, I could see a lot of people getting on board that want to bring data processing and model deployment to the edge. Just a thought!
