### ISSUE TITLE
Dart language support

### ISSUE THREAD

**Issue by mattc-eostar** [BayesWitnesses/m2cgen#165]
For those building Flutter apps that would like to be able to utilize static models trained in scikit on-device, this tool would be a perfect fit. And if the Flutter dev team decides to add a hot code push feature to the framework, models from m2cgen could be updated on the fly.

**Comment by izeigerman** [comment]
Hi @mattc-eostar! 
Thank you, TIL about Dart 👍  
Contributions are highly appreciated, please feel free to submit a PR with Dart language support. 
m2cgen already supports quite few languages so you can pick one closest to Dart and use it as a reference.

**Comment by mattc-eostar** [comment]
Great! When I have some free time I will do that. Like I mentioned, I think this could be used within the Flutter framework which would allow this code to be run on Android, iOS, Web, Windows, macOS, and embedded hardware.

**Comment by MattConflitti** [comment]
@izeigerman 
Upsetting to see this an issue within the dart-lang repo: https://github.com/dart-lang/sdk/issues/29623

Essentially, `tanh` does not exist yet in their core math lib.  I can leave it as `NotImplemented` in the interpreter, but will this make the interpreter useless or only for a select few of the sklearn models? If so, do you know which?

I would rather not try to rig my own implementation of tanh into the interpreter. And even if I could write that, would it be relatively simple to reference that code instead of pulling from the specified math lib dependency?

`interpreters/interpreter.py` seems pretty clear it looks at the math lib provided. Perhaps a mixin would work here? Granted, I am less familiar with those in Python.

Thanks!

**Comment by MattConflitti** [comment]
It looks like the query `tanh` returns results only in the svm model.

**Comment by MattConflitti** [comment]
I could see using something like: https://dart.dev/guides/language/extension-methods
And then write the code needed to compute `tanh(double radians)`, but I have no idea where that would live and how I could pull that in for the Dart interpreter.

**Comment by MattConflitti** [comment]
#167

**Comment by MattConflitti** [comment]
#167

**Comment by StrikerRUS** [comment]
Hi @MattConflitti !

> Essentially, tanh does not exist yet in their core math lib.

> And even if I could write that, would it be relatively simple to reference that code instead of pulling from the specified math lib dependency?

The same issue was for VB interpreter. You can check the following code which seems to be working:
https://github.com/BayesWitnesses/m2cgen/blob/d28cb0063ab047751bd72eb7788b109a629f9068/m2cgen/interpreters/visual_basic/interpreter.py#L68-L71
https://github.com/BayesWitnesses/m2cgen/blob/d28cb0063ab047751bd72eb7788b109a629f9068/m2cgen/interpreters/visual_basic/interpreter.py#L49-L53
https://github.com/BayesWitnesses/m2cgen/blob/d28cb0063ab047751bd72eb7788b109a629f9068/m2cgen/interpreters/visual_basic/tanh.bas#L1-L11
https://github.com/BayesWitnesses/m2cgen/blob/d28cb0063ab047751bd72eb7788b109a629f9068/MANIFEST.in#L4
Here are some references: 
- https://golang.org/src/math/tanh.go
- https://github.com/lattera/glibc/blob/master/sysdeps/ieee754/dbl-64/s_tanh.c

**Comment by MattConflitti** [comment]
Thank you so much! I will check that out right now. I will look into the different implementations. I will probably just port the visual basic code if that is already known to work!

**Comment by MattConflitti** [comment]
Thank you so much! Works like a charm! Ended up capping at (-22,22) since anything beyond that is -1 or 1 respectively in Dart. No sense making it work extra for no reason. Will be adding to pull request soon.

**Comment by izeigerman** [comment]
Thanks @StrikerRUS 👍

**Comment by StrikerRUS** [comment]
Added in #167.
