### ISSUE TITLE
Move Dart language to a different bucket of E2E tests on Travis

### ISSUE THREAD

**Issue by izeigerman** [BayesWitnesses/m2cgen#177]
Although the Dart has been configured in `.travis.yaml` I don't see it's being executed. Eg. recent master build - https://travis-ci.org/BayesWitnesses/m2cgen/jobs/660185796.
Error in the output:
```
Unknown pytest.mark.dart - is this a typo?  You can register custom marks to avoid this warning
```
CC: @StrikerRUS

**Comment by izeigerman** [comment]
Additionally it seems like it's not a great idea to put Dart into the same bucket as R, since R tests already take 24 minutes, while other buckets take ~4 and 8.5 minutes.

**Comment by izeigerman** [comment]
Oops, sorry, I've just noticed that it's there for PR builds. We should still move it to a different bucket though.

**Comment by StrikerRUS** [comment]
I'm looking into `master` jobs: https://travis-ci.org/BayesWitnesses/m2cgen/builds/660185788.
In all buckets only the first language tests are run.

**Comment by StrikerRUS** [comment]
Sorry, wrong button. Seems that PR builds are OK. Re-running the rest of `master` incomplete builds.

**Comment by izeigerman** [comment]
Hm, yeah. Super weird. Thanks for looking into this!

**Comment by StrikerRUS** [comment]
Yes, indeed...

**Comment by izeigerman** [comment]
Seems not to be the issue. Closing this for now.
