### ISSUE TITLE
sigmoid and softmax as language-specific functions

### ISSUE THREAD

**Issue by StrikerRUS** [BayesWitnesses/m2cgen#196]
Maybe it is better to require from supported languages to implement `sigmoid` and `softmax` functions than defining them as expressions? It will simplify the readability of generated code and speed it up by more efficient native implementations.

Also, we can fallback to the current expressions when functions are missed.

Why I'm rising this issue is because I think that we currently have some kind of inconsistency, requiring implementation of `Tanh` function from languages, but at the same time defining `sigmoid` as expression, while they both can be written via `Exp` function.

![image](https://user-images.githubusercontent.com/25141164/79625245-57d1c500-8130-11ea-97d7-2b66d1a2a8b4.png)

![image](https://user-images.githubusercontent.com/25141164/79625258-69b36800-8130-11ea-97cb-8a640d2f9cb7.png)

https://github.com/BayesWitnesses/m2cgen/blob/dcd62f4476daf883b04cc40a85c125dd11245cd9/m2cgen/assemblers/utils.py#L83-L100

https://github.com/BayesWitnesses/m2cgen/blob/dcd62f4476daf883b04cc40a85c125dd11245cd9/m2cgen/interpreters/visual_basic/tanh.bas#L1-L11

**Comment by izeigerman** [comment]
This is a great suggestion indeed. I agree with every point you raised. 

My only concern is that sigmoid and softmax are uncommon enough (unlike exponent and tanh) that we'll have to introduce a lot of manually written boilerplate across all languages. We already have some of it (vector multiplication for instance), but adding more will increase the support burden and reduce the ease of integration of new languages. 

Quite a few languages have been introduced by  external contributors and I'm afraid that by increasing complexity and raising the entry barrier we'll drive potential contributors away. 

Please let me know if you find my concerns valid.

**Comment by StrikerRUS** [comment]
I absolutely agree with you! As always, it is a tradeoff between complexity of adding languages and further runtime performance. However, I believe that the following my suggestion can eliminate potential  increase of entry point efforts.

> Also, we can fallback to the current expressions when functions are missed.

Moreover, it can even decrease the barrier. For example, if we had a default expression for `Tanh` function, there was no need to write custom implementation for the Dart language in #165.

To sum up, newcomers will have a choice either add very basic support of their favorite language without writing many math and statistical functions (however, I guess it won't be so hard for them as they should know that language well) relying on our inefficient fallback expressions, or code a little bit more in their favorite language and make runtime performance better. Also, it will allow to break down adding support of new language into several PRs, while preserving the support of all ML models starting from the first one.

Speaking about the current language pool, I can write all needed functions for all of them in next days. And I have a wish to do my best helping in or creating "advanced-level support" PRs for new languages.

> My only concern is that sigmoid and softmax are uncommon enough

That's true, that not so many languages have them as a built-in functions. However, at present they are used only in boosting models and according to created issues in our GitHub repo it can be said that boosting models are the most popular ones. So, I believe it's worth to increase the support burden with the aim to increase the runtime performance for those models.

**Comment by izeigerman** [comment]
Oh shoot, I overlooked this statement, sorry.

> Also, we can fallback to the current expressions when functions are missed.

Though some time after posting my comment I came to the same conclusion myself. Yes, I think this idea is fantastic 👍

**Comment by izeigerman** [comment]
@StrikerRUS one more question. Unless the implementation of those functions is provided by the standard library how exactly are we going to ensure:
> speed it up by more efficient native implementations
What will be different compared to the existing expression (with some reused/cached parts)

**Comment by StrikerRUS** [comment]
It is hard to me to give a clear answer right now.

For instance, in `Tanh` we are clipping argument range with different thresholds.

Also, it will allow to decrease the depth of binary expressions and use `BinExpressionDepthTrackingMixin` less frequent.

Maybe for some functions loops will be more suitable, idk...
