### ISSUE TITLE
Can support native xgboost.core.Booster  model?

### ISSUE THREAD

**Issue by Jie-Yuan** [BayesWitnesses/m2cgen#212]

**Comment by Jie-Yuan** [comment]
Can support native xgboost.core.Booster  model?

**Comment by StrikerRUS** [comment]
Hi @Jie-Yuan !

I believe this feature request is very close to [your previous one](#164) if you meant raw json file of the model there or even a duplicate otherwise.

Unfortunately, there has been no progress since that time I'm aware of.
