### ISSUE TITLE
Travis 50min limit... again

### ISSUE THREAD

**Issue by StrikerRUS** [BayesWitnesses/m2cgen#267]
Today I saw our jobs at `master` hit 50min Travis limit per job 3 times. Guess, it's time to either review #243 or reorganize jobs at Travis. Refer to #125 for the past experience and to #114 for some further ideas.

cc @izeigerman

**Comment by izeigerman** [comment]
Oh no. I'll prioritize the review of that PR. Thank you!

**Comment by StrikerRUS** [comment]
We have dropped Travis CI support in #272. Now we are using GitHub Actions for CI tests. It has 6 hours limit for each job and  72 hours limit for the whole workflow: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#usage-limits.
