### ISSUE TITLE
how to give input to the generated code

### ISSUE THREAD

**Issue by monisha08041998** [BayesWitnesses/m2cgen#278]
_**Error: Main method not found in class Extratreesregressor, please define the main method as:
   public static void main(String[] args)**_
or a JavaFX application class must extend javafx.application.Application
 How to run without main file and what is the input to the generated code?Kindly help im a newbie.

**Comment by StrikerRUS** [comment]
Very sorry for this project was inactive for a long time!

Please refer to the option 2 from the following comment: https://github.com/BayesWitnesses/m2cgen/issues/117#issuecomment-550418115.

Just rename `class Model` into `class Extratreesregressor` there according to the provided error log. By doing so you will have one file with one class and two methods.


For example, you have only one file named `Extratreesregressor.java`:
```java
/* Extratreesregressor.java */

public class Extratreesregressor
{
  public static void main(String[] args)
  {
    double[] features = new double[args.length];

    for (int i = 0; i < args.length; ++i)
      {
	features[i] = Double.parseDouble(args[i]);
      }
    System.out.println(score(features));
  }

  public static double score(double[] input)
  {
    return ((((36.45948838508965) + ((input[0]) * (-0.10801135783679647))) +
	     ((input[1]) * (0.04642045836688297))) +
	    ((input[2]) * (0.020558626367073608))) +
      ((input[3]) * (2.6867338193449406));
  }
}
```

Run from the command line:
```sh
javac Extratreesregressor.java
java Extratreesregressor 1.0 2.0 3.0 4.0
```

Where `1.0 2.0 3.0 4.0` is the input for the compiled program representing features of one object you'd like to score.

And the output is `47.252929100467604`.
