### ISSUE TITLE
what arguement should be passed

### ISSUE THREAD

**Issue by monisha08041998** [BayesWitnesses/m2cgen#279]
Hey @fakhrulfa! To keep things simple you may do one of the following:
1. Copy the Model.java file into your project. Create a class with the main method and invoke the generated model from it. Eg. you project structure can be something like this:
```
 | src/
 | | main/
 | | | java/
 | | | | com/
 | | | | | example/
 | | | | | | Main.java
 | | | | | | Model.java
```
Then you can invoke the `score` method from you main class:
```java
public class Main {

  public static void main(String[] args) {
     Model.score(...);
  }
}
```
2. To try the code in a quick a dirty way just add the main method to the `Model` class and run it instead:
```java
public class Model {
  public static void main(String[] args) {
    score(...)
  }

  public static double score(double[] input) {
  ...
}
```

_Originally posted by @izeigerman in https://github.com/BayesWitnesses/m2cgen/issues/117#issuecomment-550418115_

**Comment by StrikerRUS** [comment]
Answered in https://github.com/BayesWitnesses/m2cgen/issues/278#issuecomment-821741469.
