### ISSUE TITLE
Add support for multi-target regression

### ISSUE THREAD

**Issue by monisha08041998** [BayesWitnesses/m2cgen#280]

**Comment by monisha08041998** [comment]
Hi does this provide support for multilabel problems?

**Comment by sharmahemlata** [comment]
I have the same question. It is possible for the score function to return a vector instead of a single value? Is there some parameter that has to be passed to mc2gen function along with the model?

**Comment by izeigerman** [comment]
Hey @monisha08041998 and @sharmahemlata ! Thanks for bringing this topic up. 

Unfortunately there is currently no support for multitarget regressors in `m2cgen`.

**Comment by StrikerRUS** [comment]
Added into feature-request hub #491.
