### ISSUE TITLE
Add support for Isolation Forest

### ISSUE THREAD

**Issue by dirtymonkey365** [BayesWitnesses/m2cgen#330]
Please provide the transformation of isolation forest.

**Comment by StrikerRUS** [comment]
Hey @dirtymonkey365 !
Thanks for your feature request!
Could you please provide mode details about your use-case (what is the purpose of using Isolation Forest, model you use (is it [Isolation forest from scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html)?), typical model parameters, etc.) to help prioritize feature requests?

**Comment by StrikerRUS** [comment]
Added into feature-request hub #491.
