### ISSUE TITLE
Add support for CatBoost

### ISSUE THREAD

**Issue by candalfigomoro** [BayesWitnesses/m2cgen#347]
xgboost and lightgbm are already supported, supporting catboost (https://github.com/catboost/catboost) as well would be a nice addition.

**Comment by rspadim** [comment]
catboost project have some options already - https://catboost.ai/docs

Exporting models

CoreML
Python or C++
JSON
ONNX
PMML

**Comment by candalfigomoro** [comment]
@rspadim Is there a zero-dependencies JavaScript transpiler for catboost?

**Comment by StrikerRUS** [comment]
@candalfigomoro They are working on releasing a Node.js package:

![image](https://user-images.githubusercontent.com/25141164/113769202-617d7f80-9729-11eb-8b49-4797c5624604.png)


https://youtu.be/aTtD2QlQ9n0?t=2510 (41:50)

**Comment by StrikerRUS** [comment]
Added into feature-request hub #491.
