### ISSUE TITLE
Add support for Naive Bayes

### ISSUE THREAD

**Issue by rspadim** [BayesWitnesses/m2cgen#350]
Hi folks, should be possible support sklearn stacking and naives bayes?

**Comment by StrikerRUS** [comment]
Hey @rspadim !
Thanks for your feature request!
Could you please provide more details about your use-case (what is the purpose of using Naive Bayes, which one do you want to support (there are a lot of models: https://scikit-learn.org/stable/modules/naive_bayes.html), base models you use in stacking, typical model parameters, etc.) to help prioritize feature requests?

**Comment by StrikerRUS** [comment]
Also, I'd like to split this feature request into two separate requests, if you don't mind.

**Comment by rspadim** [comment]
hi, we could start with the "easy to implement" models, no problem doing it with separate issues

the idea is easily help the port of library dependent models to "lib free" codes

**Comment by StrikerRUS** [comment]
Added into feature-request hub #491.
