### ISSUE TITLE
Does m2cgen support CART algorithm?

### ISSUE THREAD

**Issue by dawangda** [BayesWitnesses/m2cgen#353]
Does m2cgen support CART (Classification and Regression Tree) algorithm?

**Comment by izeigerman** [comment]
Hey @dawangda! Yes, it does. [BothDecisionTreeClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html) and [DecisionTreeRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html) from the scikit-learn package are supported.
