### ISSUE TITLE
Multioutput random forests regressor only returns first value

### ISSUE THREAD

**Issue by ntanck** [BayesWitnesses/m2cgen#354]
Good morning! I've been trying to transpile a pickled multioutput random forests regressor model to Java, with limited success. 

Although I'm able to retrieve the first value as a double with no issues (the value even matches the Sklearn predicted value), I do believe the expected return type should be an array of doubles instead, which for some reason isn't happening.

By loading the pickle file through Python with extremely simple code, I'm able to get the following results:

Code:
```python
with open('RF_reg.pickle', 'rb') as f:
    l = pickle.load(f)

# Dummy values, in this case, just for checking for matches
print(l.predict([[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]])) 
```

Output (types extracted from each array value):
```python
<class 'numpy.float64'>
5045.0
<class 'numpy.float64'>
500.0
<class 'numpy.float64'>
109955.0
<class 'numpy.float64'>
115500.0
```

Meanwhile, the transpiled code, with the exact same features, decides to return a single double matching the first value (5045.0):
```java
[...]  // Transpiled code
    public static void main(String[] args) {
        double[] test_vals = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};
        System.out.println(score(test_vals));
    }
```
Output: `5045.0`

The transpiled code was generated through the CLI with ```m2cgen RF_reg.pickle --language java --recursion-limit 2400  --class_name RFReg > rf_gen.java``` and was also generated using the following Python code:

```python
import pickle
import m2cgen as m2c
import sys

sys.setrecursionlimit(2400)

with open('RF_reg.pickle', 'rb') as f:
    l = pickle.load(f)

code = m2c.export_to_java(l)
```

Is there something I'm forgetting or is handling multioutput RF reg. models limited in some way?

Thanks in advance

**Comment by ntanck** [comment]
For some more context and information, the number of estimators for this specific project is 250, with an output size of 4.

**Comment by StrikerRUS** [comment]
Hey @ntanck !

With your most recent corrections of the issue body it starting to be clear that you are using **multioutput random forest regressor**? I **guess** you've wrapped ordinary [`RandomForestRegressor`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html) into [`MultiOutputRegressor`](https://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html) class. Am I right? Please provide the code you used to train your model to make things completely clear.

![image](https://user-images.githubusercontent.com/25141164/113451179-1fdb9480-940a-11eb-874e-d3037f6d8beb.png)

**Comment by ntanck** [comment]
Hello, @StrikerRUS!

Unfortunately, I do not have access to the code used to train the model. It also seems like so to me as well. Printing (some) model details returns `RandomForestRegressor(max_depth=13, n_estimators=500, random_state=23)`. 

I can't confirm with absolute certainty, considering I'm limited in data I've been given, but you must be right.

**Comment by StrikerRUS** [comment]
@ntanck 
OK, thanks for your response!
Right now `m2cgen` doesn't support multi-target regression/classification, unfortunately. We already have a feature request to support it (#280), so please subscribe to that issue to be notified about any updates regarding it.
