### ISSUE TITLE
Add support for MLP from scikit-learn

### ISSUE THREAD

**Issue by rizkidewanto** [BayesWitnesses/m2cgen#431]
First of all, thanks for creating this great tool i was looking for. Will you add support for keras & neural network (MLPRegressor & MLPClassifier) from scikit-learn? Looking forward to it

**Comment by StrikerRUS** [comment]
@rizkidewanto Thanks a lot for your interest in m2cgen and kind words!
Unfortunately, there are no plans for supporting NNs. Inferencing NNs is becoming its own field now with dozens of specialized (very optimized) tools. This is beyond the scope of this project.

Speaking about `MLPRegressor` and `MLPClassifier` from scikit-learn particularly, I think we can add a support for them just to better cover estimators from the library.

**Comment by StrikerRUS** [comment]
Added into feature-request hub #491.
