### ISSUE TITLE
Add export to MATLAB

### ISSUE THREAD

**Issue by bhamadicharef** [BayesWitnesses/m2cgen#456]
Based on the export to C, I think the MATLAB one should not be too hard.

**Comment by muhammetbozkurt** [comment]
@bhamadicharef I am not sure this corresponds what you mean but  you can use exported C model in matlab/simulink using coder.ceval. 

1. export c code and save it.
    ```
        code = m2c.export_to_c(estimator)
        with open("test.c", "w") as f:
        f.write(code) 
    ```
2. create  header file. Dont forget include header in test.c.
    ```
        //test.h
        #ifndef TEST_H
        #define TEST_H
        double score(double * input);
        #endif
    ```
3. create .m file
    ```
    % test_m.m
    function y = test_m(in_data)
    
    coder.cinclude('test.h');
    y=0;
    y = coder.ceval('score', in_data); 
    end
    ```
4. generate code but before it create a dummy input for matlab to understand its type.  
    ```
    codegen test_m -args {dummy_data} test.c
    ```
5. you can take inference using
    ```
    test_m_mex(in_data)
    ```

**Comment by StrikerRUS** [comment]
Added into feature-request hub #490.
