### ISSUE TITLE
Same library for R language needed

### ISSUE THREAD

**Issue by Emilkindt** [BayesWitnesses/m2cgen#483]
Hello.

It would be great, if someone could make analogous library for R language!

Thank you!

**Comment by StrikerRUS** [comment]
@Emilkindt Thanks a lot for your kind words! I'm glad you've found this library useful.

Unfortunately, I'm not an experienced R user, so someone else should take a work to create a similar library for the R programming language. Also, that potential new library should have its own repository.
We have already had a similar discussion, please refer to #189.
