### ISSUE TITLE
Convert ML model to c#

### ISSUE THREAD

**Issue by apham15** [BayesWitnesses/m2cgen#535]
Hi. I was trying to conver my model to c#. But Neither does work. Do you have the right function in this case
`code = m2c.export_to_c#(xgb)`
 and
`code = m2c.export_to_csharp(xgb)`

**Comment by apham15** [comment]
Hi, Does anyone know how to help me in this case?

**Comment by StrikerRUS** [comment]
Hey @apham15 !

Function you need is `export_to_c_sharp()`.
