### ISSUE TITLE
What might cause an invalid load key on conversion?

### ISSUE THREAD

**Issue by gjtorikian** [BayesWitnesses/m2cgen#84]
When calling ` m2cgen tpot_classify.pkl --language go` on a perfectly fine Pickle file, I receive the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/m2cgen", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/m2cgen/cli.py", line 86, in main
    print(generate_code(args))
  File "/usr/local/lib/python3.7/site-packages/m2cgen/cli.py", line 71, in generate_code
    model = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '\x00'.
```

I'm curious if you might know what would cause this NULL byte to appear?

**Comment by izeigerman** [comment]
Hi @gjtorikian . Thanks for reporting this! Unfortunately I can't tell right away what went wrong here. Have you tried to unpickle this file in your own code and then apply `m2cgen.export_to_go` function to the unpickled object? 
This would help to eliminate (or other way around) the `argparse` file handling logic.

**Comment by gjtorikian** [comment]
Looks like

```python
def unpickle(filename):
    f = open(filename, "rb")
    d = pickle.load(f)
    f.close()
    return d
```

has the same error, so it's likely on my end.
